# Generated by Django 5.2.17 on 2026-09-23 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['blood_group'], name='profile_blood_group_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['location'], name='profile_location_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_available_for_donation'], name='profile_donor_available_idx'),
        ),
    ]
