# Generated by Django 5.2.17 on 2026-09-25 19:21

import infrastructure.storage.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_donor_group_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=infrastructure.storage.paths.profile_upload_path),
        ),
    ]
