# Generated by Django 5.2.17 on 2026-09-25 19:21

import infrastructure.storage.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_enable_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundingmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=infrastructure.storage.paths.founding_member_upload_path),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(upload_to=infrastructure.storage.paths.slider_upload_path),
        ),
    ]
