import factory

from apps.profiles.models import BloodGroup, Profile

from .user import UserFactory


class ProfileFactory(factory.django.DjangoModelFactory):
    """Reuse the profile generated by the user creation signal when present."""

    class Meta:
        model = Profile
        django_get_or_create = ("user",)

    user = factory.SubFactory(UserFactory)
    name = factory.Faker("name")
    blood_group = BloodGroup.O_POSITIVE
    location = "Dhaka"
    is_available_for_donation = True
